# -*- docker-image-name: "ashgillman/medcon" -*-
FROM debian:jessie
MAINTAINER Ashley Gillman <gillmanash@gmail.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -qy \
    medcon
